version: "3.9"

services:
#App Backend Service
  wallets_server:
    build:
      context: ./backend/wallets
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
  
# App Frontend Service  
  wallets_client:
    build:
      context: ./frontend/wallets
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - wallets_server